### ISSUE TITLE
armagarch.errors.HessianError

### ISSUE THREAD

**Issue by MarioVeloso** [iankhr/armagarch#3]
I attempted to use your package for the prediction of stock prices using the code of your example as reference. Interestingly, it seems to work fine with some stocks, but with others it generates the following error:
"armagarch.errors.HessianError: Hessian is singular! St.errors are not calculated"
Is there a way to overcome this problem?
Thanks in advance.
Regards,

**Comment by iankhr** [comment]
Hi! This error may be a sign of a misspecified model. In particular, it happens when one of the parameter estimates is esentially zero and the variance-covariance matrix cannot be calculated. Ideally, try specifying another model. 

If you still want to use the specific model, you can turn off estimation of variance-covariance matrix by setting _estimatesOnly = True_ in _fit_ as in the example below. 

```python
...
# turn off estimation of variance-covariance matrix
mdl.fit(estimatesOnly = True)
# summary will not work. Use .params to see the estimates instead
print(mdl.params)
...
```
